### ISSUE TITLE
"No such file or directory" error

### ISSUE THREAD

**Issue by seisvelas** [quietlychris/cifar-10#5]
Here's my code:

```rust
#![allow(unused_variables)]
use cifar_ten::*;

fn main() {
    let (train_data, train_labels, test_data, test_labels) = Cifar10::default()
        .show_images(true)
        .download_and_extract(true)
        .build_u8()
        .expect("Failed to build CIFAR-10 data");
}
```

With `cargo run` I get this:

```
% cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target/debug/uni`
thread 'main' panicked at 'Failed to build CIFAR-10 data: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:9:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here's how I have the dependency:

```
[dependencies]
cifar-ten = {git = "https://github.com/quietlychris/cifar-ten", branch = "master"}
```

**Comment by quietlychris** [comment]
@seisvelas Sorry for the delay; just saw this issue now. As it looks like you've seen from the changed issue title, the fix for this should be to enable the `download` option, or alternatively, already have the extracted data located in the directory specified by the `base_path` configuration. This library requires one or the other; you must either supply the data or enable the option to download it. 

You'll also probably run into an print statement saying that you don't have the `display` feature enabled. This shouldn't interfere with anything after the actual crate, unless you're somehow piping `stdout` into another progoram (it's just a print error, not a panic).

Is there a change to the crate that you were interested in have added, or more wanted to find a fix to an issue you were having?
